<a href="https://colab.research.google.com/github/aa000098/Mathmatics-for-AI/blob/hyunson/%5B%ED%8A%B9%EC%88%98%EB%8C%80%ED%95%99%EC%9B%90%5D_%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%EC%88%98%ED%95%99_%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98_(%EA%B3%BC%EC%A0%9C_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제 목표

파이썬 numpy 패키지를 이용해 스칼라, 벡터, 행렬, 텐서 간의 변환을 수행하는 코드를 작성합니다.

참고자료: [링크](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [2]:
import numpy as np

##스칼라

스칼라 $s$의 초기값을 3으로 정의하는 numpy 코드를 작성하시오.

In [7]:
# TODO
s = np.array(3)

print("s:", s)
print(np.shape(s))

s: 3
()


### 스칼라 -> 벡터

스칼라 $s$를 1-벡터 $\mathbf{v}$로 변환하는 numpy 코드를 작성하시오.

In [8]:
# TODO
v = np.array([s])

print("v:", v)
print(np.shape(v))

v: [3]
(1,)


### 스칼라 -> 행렬

스칼라 $s$를 1x1 행렬 $\mathbf{A}$로 변환하는 numpy 코드를 작성하시오.

In [9]:
# TODO
A = np.array([[s]])

print("A:", A)
print(np.shape(A))

A: [[3]]
(1, 1)


### 스칼라 -> 3-텐서

스칼라 $s$를 1x1x1 텐서 $\mathbf{T}$로 변환하는 numpy 코드를 작성하시오.

In [10]:
# TODO
T = np.array([[[s]]])

print("T:", T)
print(np.shape(T))

T: [[[3]]]
(1, 1, 1)


## 벡터

다음과 같은 초기값을 가지는 24-벡터 $\mathbf{v}$를 정의하는 numpy 코드를 작성하시오.

$$
\mathbf{v} =
\left[
\begin{array}{rrrrr}
 1 &  2 &  \cdots \ 23 & 24
\end{array}
\right]
$$

In [11]:
# 24-벡터
# TODO
v = np.arange(1, 25)

print("v:", v)
print(np.shape(v))

v: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)


### 벡터 -> 행렬

24-벡터 $\mathbf{v}$를 각각 1x24 행렬, 3x8 행렬, 6x4 행렬, 24x1 행렬 $\mathbf{A}$로 변환하는 numpy 코드를 작성하시오.

In [12]:
# 24-벡터 --> (1x24) 행렬
# TODO
A = v.reshape(1, -1)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]
A: (1, 24)


In [13]:
# 24-벡터 --> (3x8) 행렬
# TODO
A = v.reshape(3, -1)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
A: (3, 8)


In [14]:
# 24-벡터 --> (6x4) 행렬
# TODO
A = v.reshape(6, -1)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
A: (6, 4)


In [15]:
# 24-벡터 --> (24x1) 행렬

# TODO
A = v.reshape(-1, 1)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
A: (24, 1)


### 벡터 -> 3-텐서

24-벡터 $\mathbf{v}$를 2x3x4 텐서 $\mathbf{T}$로 변환하는 numpy 코드를 작성하시오.

In [16]:
# 24-벡터 --> (2x3x4) 텐서 (즉, 2개의 (3x4)행렬)
# TODO
T = v.reshape(2, 3, 4)

print("T:", T)
print("T:", np.shape(T))

T: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
T: (2, 3, 4)


### 벡터 -> 스칼라

24-벡터 $\mathbf{v}$의 모든 요소(element)를 합해, 스칼라 $s$로 나타내는 numpy 코드를 작성하시오.

In [17]:
# TODO
s = np.sum(v)

print(s)

300


## 행렬

다음의 4x3 행렬 $A$를 정의하는 numpy 코드를 작성하시오.

$$ A =
\left[
\begin{array}{rrrr}
 1 &  2 &  3 \\
 4 &  5 &  6 \\
 7 &  8 &  9 \\
10 & 11 & 12 \\
\end{array}
\right]
$$

In [19]:
# TODO
A = np.reshape(np.arange(1, 13), (4, 3))

print(A)
print(np.shape(A))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


### 행렬 -> 3-텐서

4x3 행렬 $A$를 2x3x2 텐서 $\mathbf{T}$로 변환하는 numpy 코드를 작성하시오.

In [20]:
# 4x3 행렬 --> (2x3x2) 텐서
# TODO
T = A.reshape(2, 3, 2)

print(T)
print(np.shape(T))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


### 행렬 -> 벡터

4x3 행렬 $A$를 12-벡터 $\mathbf{v}$로 변환하는 numpy 코드를 작성하시오.

In [21]:
# TODO
v = A.reshape(-1)

print(v)
print(np.shape(v))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


### 행렬 -> 스칼라

4x3 행렬 $A$의 모든 요소(element)를 합해, 스칼라 $s$로 나타내는 numpy 코드를 작성하시오.

In [22]:
# TODO
s = np.sum(A)

print(s)
print(np.shape(s))

78
()
